include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    [
      build/**,
      lib/**.freezed.dart,
      lib/**.g.dart,
      lib/**.config.dart,
      firebase_options.dart,
    ]
linter:
  rules:
    public_member_api_docs: false
